Adding fetch from response in common functions

diff --git a/common_functions b/common_functions
--- a/common_functions
+++ b/common_functions
@@ -31,3 +31,23 @@ function fn_common_fns_fetch_list_id {
 	echo
 	exit 1
 }
+
+#
+# Name: fn_common_fns_fetch_from_response
+# Purpose:
+# FETCHES FIELD VALUE FROM A JSON RESPONSE VIA REG EXPRESSION
+# ASSUMES FIELD IS UNIQUE IN RESPONSE 
+#
+# Parm : <JSON RESPONSE> <REGULAR EXPRESSION> <error response>
+#
+
+function fn_common_fns_fetch_from_response {
+	local loc_error=$3
+	if [[ $1 =~ $2 ]]; then
+		echo ${BASH_REMATCH[1]}
+	else
+		echo Error can not find match: Trello returned the following: "$1"
+		echo "$loc_error"
+		exit 1
+	fi
+}
